### ISSUE TITLE
Proper realtime comment updates

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#781]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [arunoda](https://github.com/arunoda)**
_Thursday Oct 06, 2016 at 06:27 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-comments/issues/11_

----

We need to check for new comments periodically. That's okay for now.
Later on, we need to do it with some realtime API or some hack in the comments DB.

**Comment by shilman** [comment]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arunoda](https://github.com/arunoda)**
_Sunday Oct 09, 2016 at 04:23 GMT_

----

## Tasks
- [x] Move datastore into a new class - https://github.com/kadirahq/storybook-addon-comments/pull/18
- [ ] Add streaming support to the backend.
- [ ] Add streaming support to the cloud database.
- [ ] Send new comments over the stream.

**Comment by ndelangen** [comment]
addon-comments is something we'll completely redo at some point, good feature to implement then, but for now closing.
